//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     //
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArrearsAgreementService
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="WebRequest", Namespace="http://schemas.civica.co.uk/UHWeb/2013/03")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ArrearsAgreementService.PaymentScheduleRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ArrearsAgreementService.ArrearsActionCreateRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ArrearsAgreementService.DeletePaymentScheduleRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ArrearsAgreementService.TenancyArrearsUpdateRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ArrearsAgreementService.ByReferenceRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ArrearsAgreementService.ArrearsAgreementSearchRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ArrearsAgreementService.ArrearsActionSearchRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ArrearsAgreementService.ArrearsAgreementRequest))]
    public partial class WebRequest : object
    {
        
        private string CompanyCodeField;
        
        private ArrearsAgreementService.UserCredential DirectUserField;
        
        private string MasterPasswordField;
        
        private string SessionTokenField;
        
        private string SourceSystemField;
        
        private int UserIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CompanyCode
        {
            get
            {
                return this.CompanyCodeField;
            }
            set
            {
                this.CompanyCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ArrearsAgreementService.UserCredential DirectUser
        {
            get
            {
                return this.DirectUserField;
            }
            set
            {
                this.DirectUserField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MasterPassword
        {
            get
            {
                return this.MasterPasswordField;
            }
            set
            {
                this.MasterPasswordField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SessionToken
        {
            get
            {
                return this.SessionTokenField;
            }
            set
            {
                this.SessionTokenField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string SourceSystem
        {
            get
            {
                return this.SourceSystemField;
            }
            set
            {
                this.SourceSystemField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UserId
        {
            get
            {
                return this.UserIdField;
            }
            set
            {
                this.UserIdField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserCredential", Namespace="http://schemas.civica.co.uk/UHWeb/2013/03")]
    public partial class UserCredential : object
    {
        
        private string UserNameField;
        
        private string UserPasswordField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserName
        {
            get
            {
                return this.UserNameField;
            }
            set
            {
                this.UserNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserPassword
        {
            get
            {
                return this.UserPasswordField;
            }
            set
            {
                this.UserPasswordField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PaymentScheduleRequest", Namespace="http://schemas.civica.co.uk/UHWeb/2013/03")]
    public partial class PaymentScheduleRequest : ArrearsAgreementService.WebRequest
    {
        
        private string ArrearsAgreementRefField;
        
        private ArrearsAgreementService.ArrearsScheduledPaymentInfo[] PaymentScheduleField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string ArrearsAgreementRef
        {
            get
            {
                return this.ArrearsAgreementRefField;
            }
            set
            {
                this.ArrearsAgreementRefField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public ArrearsAgreementService.ArrearsScheduledPaymentInfo[] PaymentSchedule
        {
            get
            {
                return this.PaymentScheduleField;
            }
            set
            {
                this.PaymentScheduleField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ArrearsActionCreateRequest", Namespace="http://schemas.civica.co.uk/UHWeb/2013/03")]
    public partial class ArrearsActionCreateRequest : ArrearsAgreementService.WebRequest
    {
        
        private ArrearsAgreementService.ArrearsActionInfo ArrearsActionField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public ArrearsAgreementService.ArrearsActionInfo ArrearsAction
        {
            get
            {
                return this.ArrearsActionField;
            }
            set
            {
                this.ArrearsActionField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DeletePaymentScheduleRequest", Namespace="http://schemas.civica.co.uk/UHWeb/2013/03")]
    public partial class DeletePaymentScheduleRequest : ArrearsAgreementService.WebRequest
    {
        
        private string ArrearsAgreementRefField;
        
        private int[] PaymentScheduleIdsField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string ArrearsAgreementRef
        {
            get
            {
                return this.ArrearsAgreementRefField;
            }
            set
            {
                this.ArrearsAgreementRefField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int[] PaymentScheduleIds
        {
            get
            {
                return this.PaymentScheduleIdsField;
            }
            set
            {
                this.PaymentScheduleIdsField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TenancyArrearsUpdateRequest", Namespace="http://schemas.civica.co.uk/UHWeb/2013/03")]
    public partial class TenancyArrearsUpdateRequest : ArrearsAgreementService.WebRequest
    {
        
        private ArrearsAgreementService.TenancyArrearsInfo ArrearsInfoField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public ArrearsAgreementService.TenancyArrearsInfo ArrearsInfo
        {
            get
            {
                return this.ArrearsInfoField;
            }
            set
            {
                this.ArrearsInfoField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ByReferenceRequest", Namespace="http://schemas.civica.co.uk/UHWeb/2013/03")]
    public partial class ByReferenceRequest : ArrearsAgreementService.WebRequest
    {
        
        private string ReferenceField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Reference
        {
            get
            {
                return this.ReferenceField;
            }
            set
            {
                this.ReferenceField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ArrearsAgreementSearchRequest", Namespace="http://schemas.civica.co.uk/UHWeb/2013/03")]
    public partial class ArrearsAgreementSearchRequest : ArrearsAgreementService.WebRequest
    {
        
        private ArrearsAgreementService.ArrearsAgreementSearch AgreementSearchField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public ArrearsAgreementService.ArrearsAgreementSearch AgreementSearch
        {
            get
            {
                return this.AgreementSearchField;
            }
            set
            {
                this.AgreementSearchField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ArrearsActionSearchRequest", Namespace="http://schemas.civica.co.uk/UHWeb/2013/03")]
    public partial class ArrearsActionSearchRequest : ArrearsAgreementService.WebRequest
    {
        
        private ArrearsAgreementService.ArrearsActionSearch ActionSearchField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public ArrearsAgreementService.ArrearsActionSearch ActionSearch
        {
            get
            {
                return this.ActionSearchField;
            }
            set
            {
                this.ActionSearchField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ArrearsAgreementRequest", Namespace="http://schemas.civica.co.uk/UHWeb/2013/03")]
    public partial class ArrearsAgreementRequest : ArrearsAgreementService.WebRequest
    {
        
        private ArrearsAgreementService.ArrearsAgreementInfo AgreementField;
        
        private ArrearsAgreementService.ArrearsScheduledPaymentInfo[] PaymentScheduleField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public ArrearsAgreementService.ArrearsAgreementInfo Agreement
        {
            get
            {
                return this.AgreementField;
            }
            set
            {
                this.AgreementField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public ArrearsAgreementService.ArrearsScheduledPaymentInfo[] PaymentSchedule
        {
            get
            {
                return this.PaymentScheduleField;
            }
            set
            {
                this.PaymentScheduleField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ArrearsAgreementInfo", Namespace="http://schemas.civica.co.uk/UHWeb/2013/03")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ArrearsAgreementService.ArrearsAgreementDto))]
    public partial class ArrearsAgreementInfo : ArrearsAgreementService.UserFieldEntity
    {
        
        private string ArrearsAgreementStatusCodeField;
        
        private string CommentField;
        
        private System.Nullable<System.DateTime> FcaDateField;
        
        private System.Nullable<int> FirstCheckField;
        
        private string FirstCheckFrequencyTypeCodeField;
        
        private System.Nullable<bool> IsBreachedField;
        
        private string MonitorBalanceCodeField;
        
        private System.Nullable<int> NextCheckField;
        
        private string NextCheckFrequencyTypeCodeField;
        
        private int NoPrePayField;
        
        private string ReferenceField;
        
        private System.Nullable<decimal> StartBalanceField;
        
        private System.Nullable<System.DateTime> StartDateField;
        
        private string TenancyAgreementRefField;
        
        private System.Nullable<int> ToleranceField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ArrearsAgreementStatusCode
        {
            get
            {
                return this.ArrearsAgreementStatusCodeField;
            }
            set
            {
                this.ArrearsAgreementStatusCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Comment
        {
            get
            {
                return this.CommentField;
            }
            set
            {
                this.CommentField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> FcaDate
        {
            get
            {
                return this.FcaDateField;
            }
            set
            {
                this.FcaDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> FirstCheck
        {
            get
            {
                return this.FirstCheckField;
            }
            set
            {
                this.FirstCheckField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstCheckFrequencyTypeCode
        {
            get
            {
                return this.FirstCheckFrequencyTypeCodeField;
            }
            set
            {
                this.FirstCheckFrequencyTypeCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> IsBreached
        {
            get
            {
                return this.IsBreachedField;
            }
            set
            {
                this.IsBreachedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MonitorBalanceCode
        {
            get
            {
                return this.MonitorBalanceCodeField;
            }
            set
            {
                this.MonitorBalanceCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> NextCheck
        {
            get
            {
                return this.NextCheckField;
            }
            set
            {
                this.NextCheckField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NextCheckFrequencyTypeCode
        {
            get
            {
                return this.NextCheckFrequencyTypeCodeField;
            }
            set
            {
                this.NextCheckFrequencyTypeCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NoPrePay
        {
            get
            {
                return this.NoPrePayField;
            }
            set
            {
                this.NoPrePayField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Reference
        {
            get
            {
                return this.ReferenceField;
            }
            set
            {
                this.ReferenceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> StartBalance
        {
            get
            {
                return this.StartBalanceField;
            }
            set
            {
                this.StartBalanceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> StartDate
        {
            get
            {
                return this.StartDateField;
            }
            set
            {
                this.StartDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string TenancyAgreementRef
        {
            get
            {
                return this.TenancyAgreementRefField;
            }
            set
            {
                this.TenancyAgreementRefField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Tolerance
        {
            get
            {
                return this.ToleranceField;
            }
            set
            {
                this.ToleranceField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ArrearsScheduledPaymentInfo", Namespace="http://schemas.civica.co.uk/UHWeb/2013/03")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ArrearsAgreementService.ArrearsScheduledPaymentDto))]
    public partial class ArrearsScheduledPaymentInfo : ArrearsAgreementService.UserFieldEntity
    {
        
        private System.Nullable<decimal> AmountField;
        
        private string ArrearsFrequencyCodeField;
        
        private string CommentsField;
        
        private System.Nullable<System.DateTime> EndDateField;
        
        private System.Nullable<int> IdField;
        
        private System.Nullable<System.DateTime> StartDateField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> Amount
        {
            get
            {
                return this.AmountField;
            }
            set
            {
                this.AmountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ArrearsFrequencyCode
        {
            get
            {
                return this.ArrearsFrequencyCodeField;
            }
            set
            {
                this.ArrearsFrequencyCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Comments
        {
            get
            {
                return this.CommentsField;
            }
            set
            {
                this.CommentsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> EndDate
        {
            get
            {
                return this.EndDateField;
            }
            set
            {
                this.EndDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> StartDate
        {
            get
            {
                return this.StartDateField;
            }
            set
            {
                this.StartDateField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserFieldEntity", Namespace="http://schemas.civica.co.uk/UHWeb/2013/03")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ArrearsAgreementService.ArrearsAgreementInfo))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ArrearsAgreementService.ArrearsAgreementDto))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ArrearsAgreementService.TenancyArrearsInfo))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ArrearsAgreementService.ArrearsScheduledPaymentInfo))]
    public partial class UserFieldEntity : object
    {
        
        private ArrearsAgreementService.UserField[] UserFieldListField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ArrearsAgreementService.UserField[] UserFieldList
        {
            get
            {
                return this.UserFieldListField;
            }
            set
            {
                this.UserFieldListField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ArrearsAgreementDto", Namespace="http://schemas.civica.co.uk/UHWeb/2013/03")]
    public partial class ArrearsAgreementDto : ArrearsAgreementService.ArrearsAgreementInfo
    {
        
        private ArrearsAgreementService.ArrearsScheduledPaymentDto[] PaymentScheduleField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public ArrearsAgreementService.ArrearsScheduledPaymentDto[] PaymentSchedule
        {
            get
            {
                return this.PaymentScheduleField;
            }
            set
            {
                this.PaymentScheduleField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TenancyArrearsInfo", Namespace="http://schemas.civica.co.uk/UHWeb/2013/03")]
    public partial class TenancyArrearsInfo : ArrearsAgreementService.UserFieldEntity
    {
        
        private System.Nullable<bool> CommitteeApprovedField;
        
        private System.Nullable<System.DateTime> CourtDateField;
        
        private System.Nullable<bool> CourtSummonsIssuedField;
        
        private System.Nullable<System.DateTime> EvictionDateField;
        
        private System.Nullable<bool> EvictionGrantedField;
        
        private System.Nullable<System.DateTime> NOSPExpiryDateField;
        
        private System.Nullable<bool> NOSPIssuedField;
        
        private System.Nullable<System.DateTime> NTQExpiryDateField;
        
        private System.Nullable<bool> NTQIssuedField;
        
        private System.Nullable<bool> POIssuedField;
        
        private System.Nullable<bool> SuspendedPOIssuedField;
        
        private string TenancyAgreementRefField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> CommitteeApproved
        {
            get
            {
                return this.CommitteeApprovedField;
            }
            set
            {
                this.CommitteeApprovedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> CourtDate
        {
            get
            {
                return this.CourtDateField;
            }
            set
            {
                this.CourtDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> CourtSummonsIssued
        {
            get
            {
                return this.CourtSummonsIssuedField;
            }
            set
            {
                this.CourtSummonsIssuedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> EvictionDate
        {
            get
            {
                return this.EvictionDateField;
            }
            set
            {
                this.EvictionDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> EvictionGranted
        {
            get
            {
                return this.EvictionGrantedField;
            }
            set
            {
                this.EvictionGrantedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> NOSPExpiryDate
        {
            get
            {
                return this.NOSPExpiryDateField;
            }
            set
            {
                this.NOSPExpiryDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> NOSPIssued
        {
            get
            {
                return this.NOSPIssuedField;
            }
            set
            {
                this.NOSPIssuedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> NTQExpiryDate
        {
            get
            {
                return this.NTQExpiryDateField;
            }
            set
            {
                this.NTQExpiryDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> NTQIssued
        {
            get
            {
                return this.NTQIssuedField;
            }
            set
            {
                this.NTQIssuedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> POIssued
        {
            get
            {
                return this.POIssuedField;
            }
            set
            {
                this.POIssuedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> SuspendedPOIssued
        {
            get
            {
                return this.SuspendedPOIssuedField;
            }
            set
            {
                this.SuspendedPOIssuedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string TenancyAgreementRef
        {
            get
            {
                return this.TenancyAgreementRefField;
            }
            set
            {
                this.TenancyAgreementRefField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserField", Namespace="http://schemas.civica.co.uk/UHWeb/2013/03")]
    public partial class UserField : object
    {
        
        private string KeyField;
        
        private string ValueField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Key
        {
            get
            {
                return this.KeyField;
            }
            set
            {
                this.KeyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Value
        {
            get
            {
                return this.ValueField;
            }
            set
            {
                this.ValueField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ArrearsScheduledPaymentDto", Namespace="http://schemas.civica.co.uk/UHWeb/2013/03")]
    public partial class ArrearsScheduledPaymentDto : ArrearsAgreementService.ArrearsScheduledPaymentInfo
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ArrearsActionInfo", Namespace="http://schemas.civica.co.uk/UHWeb/2013/03")]
    public partial class ArrearsActionInfo : object
    {
        
        private System.Nullable<decimal> ActionBalanceField;
        
        private string ActionCategoryField;
        
        private string ActionCodeField;
        
        private string CommentField;
        
        private System.Nullable<bool> ConfirmationField;
        
        private System.Nullable<System.DateTime> DeferredToField;
        
        private System.Nullable<bool> IsCommentOnlyField;
        
        private System.Nullable<bool> NewSetRequiredField;
        
        private string TenancyAgreementRefField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> ActionBalance
        {
            get
            {
                return this.ActionBalanceField;
            }
            set
            {
                this.ActionBalanceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ActionCategory
        {
            get
            {
                return this.ActionCategoryField;
            }
            set
            {
                this.ActionCategoryField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string ActionCode
        {
            get
            {
                return this.ActionCodeField;
            }
            set
            {
                this.ActionCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Comment
        {
            get
            {
                return this.CommentField;
            }
            set
            {
                this.CommentField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> Confirmation
        {
            get
            {
                return this.ConfirmationField;
            }
            set
            {
                this.ConfirmationField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DeferredTo
        {
            get
            {
                return this.DeferredToField;
            }
            set
            {
                this.DeferredToField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> IsCommentOnly
        {
            get
            {
                return this.IsCommentOnlyField;
            }
            set
            {
                this.IsCommentOnlyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> NewSetRequired
        {
            get
            {
                return this.NewSetRequiredField;
            }
            set
            {
                this.NewSetRequiredField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string TenancyAgreementRef
        {
            get
            {
                return this.TenancyAgreementRefField;
            }
            set
            {
                this.TenancyAgreementRefField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ArrearsAgreementSearch", Namespace="http://schemas.civica.co.uk/UHWeb/2013/03")]
    public partial class ArrearsAgreementSearch : object
    {
        
        private string HouseholdRefField;
        
        private System.Nullable<int> MaxRecordsField;
        
        private string PropertyRefField;
        
        private string ShortAddressField;
        
        private string TenancyAgreementRefField;
        
        private System.Nullable<System.DateTime> TenancyStartDateFromField;
        
        private System.Nullable<System.DateTime> TenancyStartDateToField;
        
        private string TenancyTitleField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string HouseholdRef
        {
            get
            {
                return this.HouseholdRefField;
            }
            set
            {
                this.HouseholdRefField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> MaxRecords
        {
            get
            {
                return this.MaxRecordsField;
            }
            set
            {
                this.MaxRecordsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PropertyRef
        {
            get
            {
                return this.PropertyRefField;
            }
            set
            {
                this.PropertyRefField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ShortAddress
        {
            get
            {
                return this.ShortAddressField;
            }
            set
            {
                this.ShortAddressField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TenancyAgreementRef
        {
            get
            {
                return this.TenancyAgreementRefField;
            }
            set
            {
                this.TenancyAgreementRefField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> TenancyStartDateFrom
        {
            get
            {
                return this.TenancyStartDateFromField;
            }
            set
            {
                this.TenancyStartDateFromField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> TenancyStartDateTo
        {
            get
            {
                return this.TenancyStartDateToField;
            }
            set
            {
                this.TenancyStartDateToField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TenancyTitle
        {
            get
            {
                return this.TenancyTitleField;
            }
            set
            {
                this.TenancyTitleField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ArrearsActionSearch", Namespace="http://schemas.civica.co.uk/UHWeb/2013/03")]
    public partial class ArrearsActionSearch : object
    {
        
        private System.Nullable<decimal> ActionBalanceField;
        
        private string ActionCodeField;
        
        private System.Nullable<System.DateTime> ActionDateFromField;
        
        private System.Nullable<System.DateTime> ActionDateToField;
        
        private System.Nullable<int> ActionSetField;
        
        private string CommentField;
        
        private System.Nullable<bool> CommentOnlyField;
        
        private System.Nullable<bool> LatestActionSetOnlyField;
        
        private System.Nullable<int> MaxRecordsField;
        
        private System.Nullable<int> SkipRecordsField;
        
        private bool SortAscendingField;
        
        private string TenancyAgreementRefField;
        
        private string UserNameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> ActionBalance
        {
            get
            {
                return this.ActionBalanceField;
            }
            set
            {
                this.ActionBalanceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ActionCode
        {
            get
            {
                return this.ActionCodeField;
            }
            set
            {
                this.ActionCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> ActionDateFrom
        {
            get
            {
                return this.ActionDateFromField;
            }
            set
            {
                this.ActionDateFromField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> ActionDateTo
        {
            get
            {
                return this.ActionDateToField;
            }
            set
            {
                this.ActionDateToField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> ActionSet
        {
            get
            {
                return this.ActionSetField;
            }
            set
            {
                this.ActionSetField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Comment
        {
            get
            {
                return this.CommentField;
            }
            set
            {
                this.CommentField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> CommentOnly
        {
            get
            {
                return this.CommentOnlyField;
            }
            set
            {
                this.CommentOnlyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> LatestActionSetOnly
        {
            get
            {
                return this.LatestActionSetOnlyField;
            }
            set
            {
                this.LatestActionSetOnlyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> MaxRecords
        {
            get
            {
                return this.MaxRecordsField;
            }
            set
            {
                this.MaxRecordsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> SkipRecords
        {
            get
            {
                return this.SkipRecordsField;
            }
            set
            {
                this.SkipRecordsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool SortAscending
        {
            get
            {
                return this.SortAscendingField;
            }
            set
            {
                this.SortAscendingField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string TenancyAgreementRef
        {
            get
            {
                return this.TenancyAgreementRefField;
            }
            set
            {
                this.TenancyAgreementRefField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserName
        {
            get
            {
                return this.UserNameField;
            }
            set
            {
                this.UserNameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="WebResponse", Namespace="http://schemas.civica.co.uk/UHWeb/2013/03")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ArrearsAgreementService.ArrearsActionResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ArrearsAgreementService.ArrearsAgreementListResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ArrearsAgreementService.ArrearsActionHistoryResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ArrearsAgreementService.ArrearsAgreementResponse))]
    public partial class WebResponse : object
    {
        
        private int ErrorCodeField;
        
        private string ErrorMessageField;
        
        private bool SuccessField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ErrorCode
        {
            get
            {
                return this.ErrorCodeField;
            }
            set
            {
                this.ErrorCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorMessage
        {
            get
            {
                return this.ErrorMessageField;
            }
            set
            {
                this.ErrorMessageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Success
        {
            get
            {
                return this.SuccessField;
            }
            set
            {
                this.SuccessField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ArrearsActionResponse", Namespace="http://schemas.civica.co.uk/UHWeb/2013/03")]
    public partial class ArrearsActionResponse : ArrearsAgreementService.WebResponse
    {
        
        private ArrearsAgreementService.ArrearsActionLogDto ArrearsActionField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public ArrearsAgreementService.ArrearsActionLogDto ArrearsAction
        {
            get
            {
                return this.ArrearsActionField;
            }
            set
            {
                this.ArrearsActionField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ArrearsAgreementListResponse", Namespace="http://schemas.civica.co.uk/UHWeb/2013/03")]
    public partial class ArrearsAgreementListResponse : ArrearsAgreementService.WebResponse
    {
        
        private ArrearsAgreementService.ArrearsAgreementDto[] AgreementListField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public ArrearsAgreementService.ArrearsAgreementDto[] AgreementList
        {
            get
            {
                return this.AgreementListField;
            }
            set
            {
                this.AgreementListField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ArrearsActionHistoryResponse", Namespace="http://schemas.civica.co.uk/UHWeb/2013/03")]
    public partial class ArrearsActionHistoryResponse : ArrearsAgreementService.WebResponse
    {
        
        private ArrearsAgreementService.ArrearsActionHistoryDto ArrearsHistoryField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public ArrearsAgreementService.ArrearsActionHistoryDto ArrearsHistory
        {
            get
            {
                return this.ArrearsHistoryField;
            }
            set
            {
                this.ArrearsHistoryField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ArrearsAgreementResponse", Namespace="http://schemas.civica.co.uk/UHWeb/2013/03")]
    public partial class ArrearsAgreementResponse : ArrearsAgreementService.WebResponse
    {
        
        private ArrearsAgreementService.ArrearsAgreementDto AgreementField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public ArrearsAgreementService.ArrearsAgreementDto Agreement
        {
            get
            {
                return this.AgreementField;
            }
            set
            {
                this.AgreementField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ArrearsActionLogDto", Namespace="http://schemas.civica.co.uk/UHWeb/2013/03")]
    public partial class ArrearsActionLogDto : object
    {
        
        private decimal ActionBalanceField;
        
        private string ActionCategoryField;
        
        private string ActionCodeField;
        
        private System.DateTime ActionDateField;
        
        private int ActionNoField;
        
        private int ActionSetField;
        
        private bool ConfirmationField;
        
        private System.Nullable<System.DateTime> DeferredToField;
        
        private int IdField;
        
        private bool IsCommentOnlyField;
        
        private string TenancyAgreementRefField;
        
        private string UserNameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal ActionBalance
        {
            get
            {
                return this.ActionBalanceField;
            }
            set
            {
                this.ActionBalanceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ActionCategory
        {
            get
            {
                return this.ActionCategoryField;
            }
            set
            {
                this.ActionCategoryField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ActionCode
        {
            get
            {
                return this.ActionCodeField;
            }
            set
            {
                this.ActionCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime ActionDate
        {
            get
            {
                return this.ActionDateField;
            }
            set
            {
                this.ActionDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ActionNo
        {
            get
            {
                return this.ActionNoField;
            }
            set
            {
                this.ActionNoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ActionSet
        {
            get
            {
                return this.ActionSetField;
            }
            set
            {
                this.ActionSetField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Confirmation
        {
            get
            {
                return this.ConfirmationField;
            }
            set
            {
                this.ConfirmationField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DeferredTo
        {
            get
            {
                return this.DeferredToField;
            }
            set
            {
                this.DeferredToField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsCommentOnly
        {
            get
            {
                return this.IsCommentOnlyField;
            }
            set
            {
                this.IsCommentOnlyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TenancyAgreementRef
        {
            get
            {
                return this.TenancyAgreementRefField;
            }
            set
            {
                this.TenancyAgreementRefField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserName
        {
            get
            {
                return this.UserNameField;
            }
            set
            {
                this.UserNameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ArrearsActionHistoryDto", Namespace="http://schemas.civica.co.uk/UHWeb/2013/03")]
    public partial class ArrearsActionHistoryDto : object
    {
        
        private ArrearsAgreementService.ArrearsActionLogDto[] ArrearsActionsField;
        
        private decimal CurrentBalanceField;
        
        private string HouseholdRefField;
        
        private string PropertyRefField;
        
        private string SuggestedActionField;
        
        private System.Nullable<System.DateTime> SuggestedActionDateField;
        
        private string TenancyAgreementRefField;
        
        private string TenancyTitleField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ArrearsAgreementService.ArrearsActionLogDto[] ArrearsActions
        {
            get
            {
                return this.ArrearsActionsField;
            }
            set
            {
                this.ArrearsActionsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal CurrentBalance
        {
            get
            {
                return this.CurrentBalanceField;
            }
            set
            {
                this.CurrentBalanceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string HouseholdRef
        {
            get
            {
                return this.HouseholdRefField;
            }
            set
            {
                this.HouseholdRefField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PropertyRef
        {
            get
            {
                return this.PropertyRefField;
            }
            set
            {
                this.PropertyRefField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SuggestedAction
        {
            get
            {
                return this.SuggestedActionField;
            }
            set
            {
                this.SuggestedActionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> SuggestedActionDate
        {
            get
            {
                return this.SuggestedActionDateField;
            }
            set
            {
                this.SuggestedActionDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TenancyAgreementRef
        {
            get
            {
                return this.TenancyAgreementRefField;
            }
            set
            {
                this.TenancyAgreementRefField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TenancyTitle
        {
            get
            {
                return this.TenancyTitleField;
            }
            set
            {
                this.TenancyTitleField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://schemas.civica.co.uk/UHWeb/2013/03", ConfigurationName="ArrearsAgreementService.IArrearsAgreementService")]
    public interface IArrearsAgreementService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.civica.co.uk/UHWeb/2013/03/IArrearsAgreementService/CreateArrearsA" +
            "greement", ReplyAction="http://schemas.civica.co.uk/UHWeb/2013/03/IArrearsAgreementService/CreateArrearsA" +
            "greementResponse")]
        System.Threading.Tasks.Task<ArrearsAgreementService.ArrearsAgreementResponse> CreateArrearsAgreementAsync(ArrearsAgreementService.ArrearsAgreementRequest dto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.civica.co.uk/UHWeb/2013/03/IArrearsAgreementService/AddPaymentSche" +
            "dule", ReplyAction="http://schemas.civica.co.uk/UHWeb/2013/03/IArrearsAgreementService/AddPaymentSche" +
            "duleResponse")]
        System.Threading.Tasks.Task<ArrearsAgreementService.ArrearsAgreementResponse> AddPaymentScheduleAsync(ArrearsAgreementService.PaymentScheduleRequest dto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.civica.co.uk/UHWeb/2013/03/IArrearsAgreementService/CreateArrearsA" +
            "ction", ReplyAction="http://schemas.civica.co.uk/UHWeb/2013/03/IArrearsAgreementService/CreateArrearsA" +
            "ctionResponse")]
        System.Threading.Tasks.Task<ArrearsAgreementService.ArrearsActionResponse> CreateArrearsActionAsync(ArrearsAgreementService.ArrearsActionCreateRequest dto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.civica.co.uk/UHWeb/2013/03/IArrearsAgreementService/DeletePaymentS" +
            "chedule", ReplyAction="http://schemas.civica.co.uk/UHWeb/2013/03/IArrearsAgreementService/DeletePaymentS" +
            "cheduleResponse")]
        System.Threading.Tasks.Task<ArrearsAgreementService.ArrearsAgreementResponse> DeletePaymentScheduleAsync(ArrearsAgreementService.DeletePaymentScheduleRequest dto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.civica.co.uk/UHWeb/2013/03/IArrearsAgreementService/UpdateArrearsA" +
            "greement", ReplyAction="http://schemas.civica.co.uk/UHWeb/2013/03/IArrearsAgreementService/UpdateArrearsA" +
            "greementResponse")]
        System.Threading.Tasks.Task<ArrearsAgreementService.ArrearsAgreementResponse> UpdateArrearsAgreementAsync(ArrearsAgreementService.ArrearsAgreementRequest dto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.civica.co.uk/UHWeb/2013/03/IArrearsAgreementService/UpdateTenancyA" +
            "greement", ReplyAction="http://schemas.civica.co.uk/UHWeb/2013/03/IArrearsAgreementService/UpdateTenancyA" +
            "greementResponse")]
        System.Threading.Tasks.Task<ArrearsAgreementService.WebResponse> UpdateTenancyAgreementAsync(ArrearsAgreementService.TenancyArrearsUpdateRequest dto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.civica.co.uk/UHWeb/2013/03/IArrearsAgreementService/GetArrearsAgre" +
            "ementByRef", ReplyAction="http://schemas.civica.co.uk/UHWeb/2013/03/IArrearsAgreementService/GetArrearsAgre" +
            "ementByRefResponse")]
        System.Threading.Tasks.Task<ArrearsAgreementService.ArrearsAgreementResponse> GetArrearsAgreementByRefAsync(ArrearsAgreementService.ByReferenceRequest dto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.civica.co.uk/UHWeb/2013/03/IArrearsAgreementService/GetArrearsAgre" +
            "ementList", ReplyAction="http://schemas.civica.co.uk/UHWeb/2013/03/IArrearsAgreementService/GetArrearsAgre" +
            "ementListResponse")]
        System.Threading.Tasks.Task<ArrearsAgreementService.ArrearsAgreementListResponse> GetArrearsAgreementListAsync(ArrearsAgreementService.ArrearsAgreementSearchRequest dto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.civica.co.uk/UHWeb/2013/03/IArrearsAgreementService/GetArrearsActi" +
            "onHistory", ReplyAction="http://schemas.civica.co.uk/UHWeb/2013/03/IArrearsAgreementService/GetArrearsActi" +
            "onHistoryResponse")]
        System.Threading.Tasks.Task<ArrearsAgreementService.ArrearsActionHistoryResponse> GetArrearsActionHistoryAsync(ArrearsAgreementService.ArrearsActionSearchRequest dto);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    public interface IArrearsAgreementServiceChannel : ArrearsAgreementService.IArrearsAgreementService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    public partial class ArrearsAgreementServiceClient : System.ServiceModel.ClientBase<ArrearsAgreementService.IArrearsAgreementService>, ArrearsAgreementService.IArrearsAgreementService
    {
        
    /// <summary>
    /// Implement this partial method to configure the service endpoint.
    /// </summary>
    /// <param name="serviceEndpoint">The endpoint to configure</param>
    /// <param name="clientCredentials">The client credentials</param>
    static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public ArrearsAgreementServiceClient() : 
                base(ArrearsAgreementServiceClient.GetDefaultBinding(), ArrearsAgreementServiceClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IArrearsAgreementService.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ArrearsAgreementServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(ArrearsAgreementServiceClient.GetBindingForEndpoint(endpointConfiguration), ArrearsAgreementServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ArrearsAgreementServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(ArrearsAgreementServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ArrearsAgreementServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(ArrearsAgreementServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ArrearsAgreementServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<ArrearsAgreementService.ArrearsAgreementResponse> CreateArrearsAgreementAsync(ArrearsAgreementService.ArrearsAgreementRequest dto)
        {
            return base.Channel.CreateArrearsAgreementAsync(dto);
        }
        
        public System.Threading.Tasks.Task<ArrearsAgreementService.ArrearsAgreementResponse> AddPaymentScheduleAsync(ArrearsAgreementService.PaymentScheduleRequest dto)
        {
            return base.Channel.AddPaymentScheduleAsync(dto);
        }
        
        public System.Threading.Tasks.Task<ArrearsAgreementService.ArrearsActionResponse> CreateArrearsActionAsync(ArrearsAgreementService.ArrearsActionCreateRequest dto)
        {
            return base.Channel.CreateArrearsActionAsync(dto);
        }
        
        public System.Threading.Tasks.Task<ArrearsAgreementService.ArrearsAgreementResponse> DeletePaymentScheduleAsync(ArrearsAgreementService.DeletePaymentScheduleRequest dto)
        {
            return base.Channel.DeletePaymentScheduleAsync(dto);
        }
        
        public System.Threading.Tasks.Task<ArrearsAgreementService.ArrearsAgreementResponse> UpdateArrearsAgreementAsync(ArrearsAgreementService.ArrearsAgreementRequest dto)
        {
            return base.Channel.UpdateArrearsAgreementAsync(dto);
        }
        
        public System.Threading.Tasks.Task<ArrearsAgreementService.WebResponse> UpdateTenancyAgreementAsync(ArrearsAgreementService.TenancyArrearsUpdateRequest dto)
        {
            return base.Channel.UpdateTenancyAgreementAsync(dto);
        }
        
        public System.Threading.Tasks.Task<ArrearsAgreementService.ArrearsAgreementResponse> GetArrearsAgreementByRefAsync(ArrearsAgreementService.ByReferenceRequest dto)
        {
            return base.Channel.GetArrearsAgreementByRefAsync(dto);
        }
        
        public System.Threading.Tasks.Task<ArrearsAgreementService.ArrearsAgreementListResponse> GetArrearsAgreementListAsync(ArrearsAgreementService.ArrearsAgreementSearchRequest dto)
        {
            return base.Channel.GetArrearsAgreementListAsync(dto);
        }
        
        public System.Threading.Tasks.Task<ArrearsAgreementService.ArrearsActionHistoryResponse> GetArrearsActionHistoryAsync(ArrearsAgreementService.ArrearsActionSearchRequest dto)
        {
            return base.Channel.GetArrearsActionHistoryAsync(dto);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IArrearsAgreementService))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IArrearsAgreementService))
            {
                return new System.ServiceModel.EndpointAddress("http://lbhuhwwebp01/civica-uh-gateway-test/webservices/ArrearsAgreementService.svc" +
                        "");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return ArrearsAgreementServiceClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IArrearsAgreementService);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return ArrearsAgreementServiceClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IArrearsAgreementService);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IArrearsAgreementService,
        }
    }
}
